### PR TITLE
Custom inputs

### PR DESCRIPTION
**Pull request by jhrehanoaa**

### CODE REVIEW

**Comment by jameshalgren** [comment]
@jhrehanoaa 
Note: #185 will interact with this PR. Let's coordinate at your convenience.

**Review by jhrehanoaa — COMMENTED** [review]
The yaml changes are already made in the current #185 PR. I do not believe anything needs to be amended.

**Review by jhrehanoaa — COMMENTED** [review]
adding the cmd line --wrf_hydro_channel_restart_file etc. to other pull request. #185

**Comment by jameshalgren** [comment]
Closing. Replaced by material in #185, as noted.

**Pull request closed without merging**
