### PR TITLE
Build system updates for Intel compilers

### PR DESCRIPTION
**Pull request by mattw-nws**
Believed minimal set of changes to allow compilation with Intel (other?) compilers.

## Additions

- Mainly added the ability to specify the compiler and build environment settings via environment variables
- Some capability to control compiler flags to Cython extension building pipelines
- A few `void` return types that weren't C-spec that the compilers complained about

## Removals

- Explicit references to gcc, gfortran, libgfortran etc.

## Changes

- Nothing functional

## Testing

1. Tested with Intel OneAPI 2022.3.0 and also with GCC8 suite.
2. Integration test on [NOAA-OWP/ngen](https://github.com/NOAA-OWP/ngen/actions/runs/4512264572/jobs/7945473202)
3. Test case added that can be used with ngen+t-route master branch in `data/gauge_01073000` in [ngen PR#502](https://github.com/NOAA-OWP/ngen/pull/502/files)

## Notes

-

## Todos

- 

## Checklist

- [X] PR has an informative and human-readable title
- [X] Changes are limited to a single goal (no scope creep)
- [X] Code can be automatically merged (no conflicts)
- [X] Code follows project standards (link if applicable)
- [X] Passes all existing automated tests
- [X] Any _change_ in functionality is tested
- [X] New functions are documented (with a description, list of inputs, and expected output)
- [X] Placeholder code is flagged / future todos are captured in comments
- [X] Visually tested in supported browsers and devices (see checklist below :point_down:)
- [X] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)
- [X] Reviewers requested with the [Reviewers tool](https://help.github.com/articles/requesting-a-pull-request-review/) :arrow_right:

### Target Environment support

- [X] Linux

### CODE REVIEW

**Comment by shorvath-noaa** [comment]
@mattw-nws When I try compiling this on apd-dev1 I get the following error:

```
(base) ./compiler.sh
using F90=gfortran
using CC=gcc
using NETCDFINC=/usr/include/openmpi-x86_64/
rm -f *.o *.mod
gfortran -g -c -O2 -fPIC -lgfortran -lgcc -static-gfortran -static-libgcc -no-defaultlibs varPrecision.f90
gfortran: error: unrecognized command line option ‘-static-gfortran’
gfortran: error: unrecognized command line option ‘-no-defaultlibs’
make: *** [precis.mod] Error 1
```

**Comment by mattw-nws** [comment]
@shorvath-noaa thanks... what's your `gcc --version` for that run? Admittedly I haven't tested in <GCC8. Though those flags were in the previous code... it may now be passing them to the linker or compiler where it was only passing to the other previously though.

**Comment by shorvath-noaa** [comment]
@mattw-nws 
```
(base) gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by mattw-nws** [comment]
🤦 @shorvath-noaa Missed commit in my GCC-environment working copy. Please pull and try again.

**Comment by shorvath-noaa** [comment]
Successfully compiled and ran LowerColorado_TX/test_AnA.yaml

**Pull request merged**
