### PR TITLE
Initial condition in v2 (cython) python routing framework

### PR DESCRIPTION
**Pull request by awlostowski-noaa**
## PR objective and rationale
The objective of this pull request is to update the version 02 routing module to allow warm starts (i.e. initial conditions). Warm start capabilities are essential for operational model use. 

## Proposed changes to existing codebase
1. [`mc_reach.pyx`](https://github.com/NOAA-OWP/t-route/blob/b447e80043ab62fa47914cb06b6420b5c314921d/src/python_routing_v02/fast_reach/mc_reach.pyx) now requires an initial conditions array to be passed to `compute_network` as an argument. It follows that initial conditions data are used to start simulations in place of arbitrary zero flow and zero velocity values. 
2. [`mc_reach.pyx.compute_reach_kernel`](https://github.com/NOAA-OWP/t-route/blob/b447e80043ab62fa47914cb06b6420b5c314921d/src/python_routing_v02/fast_reach/mc_reach.pyx) can now obey the short timestep assumption.
3.  [`nhd_io.get_stream_restart_from_wrf_hydro`](https://github.com/NOAA-OWP/t-route/blob/b447e80043ab62fa47914cb06b6420b5c314921d/src/python_framework_v02/nhd_io.py) now returns an n x 3 DataFrame, where n = number of segment IDs and 3 columns for qu0, qd0, and h0. Previously an n x 4 DataFrame was returned that contained a superfluous index column that was never used. 
4. [`pocono1_warmstart_v2.ipynb`](https://github.com/NOAA-OWP/t-route/blob/b447e80043ab62fa47914cb06b6420b5c314921d/notebooks/pocono1_warmstart_v2.ipynb) illustrates the utility of the modifications 1 -3, and conducts a parity test that proves version 02 routing can re-create WRF-Hydro routing output generated for the Pocono2 test domain. 

## Related issues resolved upon merge
#156 describes the necessity of the short timestep assumption in reproducing WRF-Hydro routing results. The commentary on this issue provides a detailed account of why and how the short timestep assumption is now enabled in v02. Additionally, parity test plots are shown. 
#119 - In the example notebook, WRF lateral flow data are read from CHRTOUT files and passed to `mc_reach.compute_network`. 
#120 - The sustentative changes considered in the PR allow initial states to be passed to and handled by v02 routing.

### CODE REVIEW

**Comment by jameshalgren** [comment]
Related to and may supersede #135

**Comment by awlostowski-noaa** [comment]
## Review recommendations
1. Take a look at changes made to `mc_reach.pyx`, Notice how the short timestep assumption is now enabled in `comute_reach_kernel` and initial conditions are now enabled in `compute_network`. New comments in the code explain the rationale behind each change. 
2. Open [`pocono1_warmstart_v2.ipynb`](https://github.com/NOAA-OWP/t-route/blob/b447e80043ab62fa47914cb06b6420b5c314921d/notebooks/pocono1_warmstart_v2.ipynb) and run with Google Colab. Notice how WRF Hydro lateral flow and initial conditions data are imported and passed through arguments to `mc_reach.compute_network`. Critically, take note that the changes made almost perfectly reproduce WRF-Hydro channel flow results for the Pocono test case. The plot produced in the final cell compares simulation results at the network tailwater (4186169). Go ahead and change the `compare_node` variable to compare simulations at other nodes in the network.

**Comment by awlostowski-noaa** [comment]
# HOLD
Need to change test scripts and conceptual notebooks to acknowledge the new arguments required in `mc_reach.compute_network`

**Comment by awlostowski-noaa** [comment]
# RESUME
Dependent notebooks and scripts that run `mc_reach.compute_network` are modified to pass initial condition argument. At this time, initial conditions in these pieces of example code are assumed to be zero.
- `compute_nhd_routing_SingleSeg_v02.py`
- `compute-network-v2.ipynb`

**Review by jameshalgren — DISMISSED** [review]
Please add a table to the notebook and switch the repo reference to NOAA-OWP. Thanks.

**Comment by awlostowski-noaa** [comment]
@jameshalgren ready to merge?

**Review by jameshalgren — APPROVED** [review]

**Pull request merged**
