### PR TITLE
[WIP] [Hold for delete] Add c/cython-only version of mc algorithm

### PR DESCRIPTION
**Pull request by jameshalgren**
To better understand the opportunity for maximum optimization of the routing performance (which will be useful for any algorithm implemented), attempting to add a cython-only version of the MC algorithm.

### CODE REVIEW

**Comment by groutr** [comment]
@jameshalgren I'm getting errors trying to run the computation. There is something wrong with levelpool.
```
ImportError: /home/grout/projects/t-route-new/src/python_framework_v02/troute/network/reservoirs/levelpool/levelpool.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _gfortran_os_error_at
```
I've tried recompiling several times, but I can't get the error to go away.

**Comment by groutr** [comment]
I was able to work around the issue. Since I don't have the datafiles for Florence test case, I did the Pocono test case. It runs in just over .5s on my laptop.

**Comment by hellkite500** [comment]
@groutr 
> @jameshalgren I'm getting errors trying to run the computation. There is something wrong with levelpool.
> 
> ```
> ImportError: /home/grout/projects/t-route-new/src/python_framework_v02/troute/network/reservoirs/levelpool/levelpool.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _gfortran_os_error_at
> ```
> 
> I've tried recompiling several times, but I can't get the error to go away.

This looks like the gfortran library isn't available to the linker at runtime, might try pointing $LD_LIBRARY_PATH to wherever it was installed and see if that helps when running.  Was something like that your workaround or did you do something different?

**Comment by jameshalgren** [comment]
I worked around it commenting lines referring to the fortran libraries. But I assume this leaves some dangerous holes in the reservoir module: 

```
src/python_routing_v02> git diff
diff --git a/src/fortran_routing/Reservoir_Binding/Reservoirs/makefile b/src/fortran_routing/Reservoir_Binding/Reservoirs/makefile
index 2175485..59c9b0a 100644
--- a/src/fortran_routing/Reservoir_Binding/Reservoirs/makefile
+++ b/src/fortran_routing/Reservoir_Binding/Reservoirs/makefile
@@ -1,16 +1,16 @@
-NETCDFINC       :=       $(NETCDF_INC)
-NETCDFLIB       =       -L$(NETCDF_LIB) -lnetcdff -lnetcdf
+#NETCDFINC       :=       $(NETCDF_INC)
+#NETCDFLIB       =       -L$(NETCDF_LIB) -lnetcdff -lnetcdf
 COMPILER90 = gfortran
 F90FLAGS = -w -c -ffree-form -ffree-line-length-none -fconvert=big-endian -frecord-marker=4
 F90FLAGS := -g $(F90FLAGS) -I$(NETCDFINC) -static-libgfortran -static-libgcc -nodefaultlibs -lgfortran -lgcc -fPIC
 AR = ar
 ARFLAGS = rc

-VPATH = ./Level_Pool ./Persistence_Level_Pool_Hybrid ./RFC_Forecasts
+VPATH = ./Level_Pool # ./Persistence_Level_Pool_Hybrid ./RFC_Forecasts

 .PHONY: all install install_lp

-all: binding_lp.a bind_hybrid.a bind_rfc.a
+all: binding_lp.a # bind_hybrid.a bind_rfc.a

 test_main: test_main.o binding_lp.a bind_hybrid.a bind_rfc.a
        gfortran -g -o $@ $^
diff --git a/src/python_framework_v02/setup.py b/src/python_framework_v02/setup.py
index 6e97f22..2f1590d 100644
--- a/src/python_framework_v02/setup.py
+++ b/src/python_framework_v02/setup.py
@@ -46,7 +46,7 @@ reservoirs = Extension(
              ],
     include_dirs=[np.get_include()],
     extra_objects=["./libs/binding_lp.a"],
-    libraries=["gfortran", "netcdff", "netcdf"],
+    libraries=["gfortran"],  # "netcdff", "netcdf"],
     extra_compile_args=["-g"],
 )

lines 1-38/38 (END)
```

**Comment by groutr** [comment]
@hellkite500 setting LD_LIBRARY_PATH doesn't seem to change any behavior. I still get the same missing symbol error.
```
❯ ldd levelpool.cpython-37m-x86_64-linux-gnu.so
        linux-vdso.so.1 (0x00007ffd43098000)
        libgfortran.so.5 => xxxxxxxxxxx/miniconda3/envs/wrf3/lib/libgfortran.so.5 (0x00007f10e4fca000)
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f10e4f6c000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007f10e4d9f000)
        libquadmath.so.0 => xxxxxxxxxx/miniconda3/envs/wrf3/lib/libquadmath.so.0 (0x00007f10e4d65000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007f10e4c20000)
        libgcc_s.so.1 => xxxxxxxxxx/miniconda3/envs/wrf3/lib/libgcc_s.so.1 (0x00007f10e4c0a000)
        /usr/lib64/ld-linux-x86-64.so.2 (0x00007f10e519c000)
❯ LD_LIBRARY_PATH=xxxxxxxx/miniconda3/envs/wrf3/lib python compute_nhd_routing_SingleSeg_v02.py -f ../../test/input/yaml/Florence_Benchmark.yaml
Traceback (most recent call last):
  File "compute_nhd_routing_SingleSeg_v02.py", line 297, in <module>
    import fast_reach
  File "fast_reach/mc_reach.pyx", line 1, in init fast_reach
    # cython: language_level=3, boundscheck=True, wraparound=False, profile=True
ImportError: xxxxxxxxx/t-route-new/src/python_framework_v02/troute/network/reservoirs/levelpool/levelpool.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _gfortran_os_error_at
```

**Comment by hellkite500** [comment]
> undefined symbol: _gfortran_os_error_at

I would double check that the same conda libs are used in the build steps.  Is it possible the library was built/linked against a different gcc/gfortran (system compiler maybe?)

**Comment by jameshalgren** [comment]
Superseded by #299

**Pull request closed without merging**
