### PR TITLE
Diffusive wave capability update package 

### LINKED ISSUE #340: reservoir initial states not written to `flowveldepth`
ping @jameshalgren @jdmattern-noaa 

Reservoir initial outflow conditions are not written to the `flowveldepth_nd` array in [`compute_network_structured`](https://github.com/NOAA-OWP/t-route/blob/498c5fddf20c4a09b10f0426728fe45332f108b7/src/python_routing_v02/troute/routing/fast_reach/mc_reach.pyx#L983). This is problematic because stream reaches downstream of reservoirs are not reading the appropriate boundary conditions for the first timestep. 

The Muskingum-Cunge `compute_reach_kernel` requires data for upstream flows at the previous timestep and upstream flows at the current timestep. Because reservoir initial states are never written to `flowveldepth_nd`, then, for the first timestep, upstream flows and previous upstream flow values are taken to be zero for stream reaches downstream of a reservoir. 

So, why doesn't this bug cause failure of our parity tests? My hunch is that the memory of this error is really brief. Errors caused by this bug will only be noticed in reaches immediately downstream of a reservoir for the very first few timesteps of a simulation.

# Possible solutions
1. Definitely need to write reservoir initial states to `flowveldepth_nd`, and I suggest we do that [here](https://github.com/NOAA-OWP/t-route/blob/498c5fddf20c4a09b10f0426728fe45332f108b7/src/python_routing_v02/troute/routing/fast_reach/mc_reach.pyx#L1070)
2. If waterbody reaches are in the offnetwork upstream group, then populate `flowveldepth_nd` from the waterbody parameters dataframe. That would happen by editing [these lines](https://github.com/NOAA-OWP/t-route/blob/498c5fddf20c4a09b10f0426728fe45332f108b7/src/python_routing_v02/troute/routing/fast_reach/mc_reach.pyx#L1181-L1182) with a conditional statement that comprehends if the segment ID is a waterbody or not.

### PR DESCRIPTION
**Pull request by awlostowski-noaa**
# Subnetwork construction between waterbodies
A new function, named [`build_subnetworks_btw_reservoirs`](https://github.com/awlostowski-noaa/t-route/blob/cf0054b83fe0935d90b4e01d0efd95830e923cb5/src/python_framework_v02/troute/nhd_network.py#L597-L692), in `nhd_network` builds subnetworks between waterbodies. The function uses the same breadth first search approach as the `build_subnetworks` and `dfs_decomposition` functions, but imposes subnetwork break points to be at waterbodies. 

#344 is included in this pull request.

# New parallel compute method developed to handle diffusive wave with reservoirs
A new parallel compute method, named ["by-subnetwork-diffusive"](https://github.com/awlostowski-noaa/t-route/blob/cf0054b83fe0935d90b4e01d0efd95830e923cb5/src/python_routing_v02/troute/routing/compute.py#L553-L761),  is included in `compute.py`. This method is very similar to other "by-subnetwork" parallel compute methods in that subnetworks of common orders are evaluated in parallel. However, even numbered orders are stream networks and odd numbered orders are reservoirs. The compute function is switched at every order iteration between `diffusive`, which is used to evaluate subnetworks with the diffusive wave model, and `V02-structured`, which is used to evaluate reservoirs. 

Lower boundary flows from diffusive wave simulations provide the upper boundary conditions for reservoir simulations. Similarly, lower boundary flows from reservoir simulations provide upper boundary conditions for downstream diffusive wave simulations. At this time, a normal depth approximation is used at the downstream boundary of diffusive wave simulations (i.e. at reservoir inflow points or network tail waters). 

# Correct initial condition specifications for reservoir nodes
During the development of the "by-subnetwork-diffusive" parallel compute method, we realized that initial conditions were not being correctly assigned to reservoir nodes. This was partially corrected by #345. This pull requests completes the solution by correctly assigning reservoir initial states in the case when reservoir are off-network upstream nodes in a by-subnetwork parallel simulation. This should resolve #340.  

# Initial flow conditions from WRF Hydro
Initial flow conditions are now passed from WRF-Hydro restart files down the the diffusive wave kernel. Previously, the diffusive wave model was initialized with some arbitrary flow rate. While the capability to pass and use initial flows from WRF-Hydro restart files is a step in the right direction, it is not a complete solution. The diffusive wave model requires initial state for flow, celerity, and diffusivity. So, even though flow conditions are initialized, celerity and diffusivity are still initialized arbitrarily, which mandates a model spin-up period before reasonable simulation results are generated. A new issue is opened to encourage more thinking on how we should initialize diffusive wave simulations --> #348 . 

# Tulane (variable timestep) version of diffusive wave model kernel
The diffusive wave kernel was replaced with the variable timestep solution developed by JTTI collaborators at Tulane University. The input and output data structures are identical to the previous version.

# Testing
```
# compile changes in cython and fortran code
./compiler.sh
```
## Check that "by-subnetwork-diffusive" parallel scheme is correctly ordered
```
# set compute_kernel: V02-structured in Croton_NY_levelpool_diffusive.yaml. Expect parity with WRF-Hydro
python -m nwm_routing -V2 -f ../../test/input/yaml/Croton_NY_levelpool_diffusive.yaml
```
## Simulate Croton domain with diffusive wave
```
# set compute_kernel: diffusive in Croton_NY_levelpool_diffusive.yaml.
# Do NOT expect parity with WRF Hydro. Simply expect real numbers returned. 
python -m nwm_routing -V2 -f ../../test/input/yaml/Croton_NY_levelpool_diffusive.yaml
```
## make sure other tests don't break
```
# set return_courant: False in Florence_Benchmark.yaml
python -m nwm_routing -V2 -f ../../test/input/yaml/Florence_Benchmark.yaml
```
```
python -m nwm_routing -V2 -f ../../test/input/yaml/CustomInput.yaml
```
```
python -m nwm_routing -V2 -f ../../test/input/yaml/Croton_NY_levelpool.yaml
```
```
python -m nwm_routing -V2 -f ../../test/input/yaml/Croton_NY_hybrid_usgs.yaml
```
```
python -m nwm_routing -V2 -f ../../test/input/yaml/Croton_NY_rfc.yaml
```

### CODE REVIEW

**Comment by jhrehanoaa** [comment]
One of the test cases failed. Looking at it now. Results for every run are below. 


python -m nwm_routing -V2 -f ../../test/input/yaml/Croton_NY_levelpool_diffusive.yaml


conducting parity check, comparing WRF Hydro results against t-route results
                     flow, wrf (cms)  flow, t-route (cms)      diff   absdiff
2011-08-26 01:00:00         0.810436             0.858823 -0.048387  0.048387
2011-08-26 02:00:00         0.810048             0.866536 -0.056488  0.056488
2011-08-26 03:00:00         0.810331             0.872421 -0.062090  0.062090
2011-08-26 04:00:00         0.811515             0.880949 -0.069434  0.069434
2011-08-26 05:00:00         0.813122             0.891472 -0.078350  0.078350
2011-08-26 06:00:00         0.815026             0.902315 -0.087290  0.087290
2011-08-26 07:00:00         0.817127             0.911992 -0.094865  0.094865
2011-08-26 08:00:00         0.818988             0.920234 -0.101246  0.101246
2011-08-26 09:00:00         0.820710             0.927731 -0.107020  0.107020
2011-08-26 10:00:00         0.823016             0.933983 -0.110967  0.110967
2011-08-26 11:00:00         0.825198             0.938941 -0.113743  0.113743
2011-08-26 12:00:00         0.827037             0.918077 -0.091040  0.091040
2011-08-26 13:00:00         0.803451             0.918458 -0.115007  0.115007
2011-08-26 14:00:00         0.802600             0.919630 -0.117030  0.117030
2011-08-26 15:00:00         0.802963             0.921072 -0.118110  0.118110
2011-08-26 16:00:00         0.803524             0.922558 -0.119034  0.119034
2011-08-26 17:00:00         0.804237             0.924151 -0.119915  0.119915
2011-08-26 18:00:00         0.805158             0.925775 -0.120617  0.120617
2011-08-26 19:00:00         0.806179             0.927400 -0.121221  0.121221
2011-08-26 20:00:00         0.807236             0.929197 -0.121960  0.121960
2011-08-26 21:00:00         0.808481             0.931298 -0.122817  0.122817
2011-08-26 22:00:00         0.810025             0.934017 -0.123992  0.123992
2011-08-26 23:00:00         0.812141             0.938841 -0.126700  0.126700
2011-08-27 00:00:00         0.816546             0.943660 -0.127114  0.127114
       flow, wrf (cms)  flow, t-route (cms)       diff    absdiff
count        24.000000            24.000000  24.000000  24.000000
mean          0.811879             0.914980  -0.103102   0.103102
std           0.007246             0.023804   0.024046   0.024046
min           0.802600             0.858823  -0.127114   0.048387
25%           0.805924             0.909573  -0.120768   0.090102
50%           0.810383             0.921815  -0.114375   0.114375
75%           0.816691             0.929722  -0.090102   0.120768
max           0.827037             0.943660  -0.048387   0.127114


python -m nwm_routing -V2 -f ../../test/input/yaml/Croton_NY_levelpool_diffusive.yaml

                     flow, wrf (cms)  flow, t-route (cms)      diff   absdiff
2011-08-26 01:00:00         0.810436             0.858823 -0.048387  0.048387
2011-08-26 02:00:00         0.810048             0.866536 -0.056488  0.056488
2011-08-26 03:00:00         0.810331             0.872421 -0.062090  0.062090
2011-08-26 04:00:00         0.811515             0.880949 -0.069434  0.069434
2011-08-26 05:00:00         0.813122             0.891472 -0.078350  0.078350
2011-08-26 06:00:00         0.815026             0.902315 -0.087290  0.087290
2011-08-26 07:00:00         0.817127             0.911992 -0.094865  0.094865
2011-08-26 08:00:00         0.818988             0.920234 -0.101246  0.101246
2011-08-26 09:00:00         0.820710             0.927731 -0.107020  0.107020
2011-08-26 10:00:00         0.823016             0.933983 -0.110967  0.110967
2011-08-26 11:00:00         0.825198             0.938941 -0.113743  0.113743
2011-08-26 12:00:00         0.827037             0.918077 -0.091040  0.091040
2011-08-26 13:00:00         0.803451             0.918458 -0.115007  0.115007
2011-08-26 14:00:00         0.802600             0.919630 -0.117030  0.117030
2011-08-26 15:00:00         0.802963             0.921072 -0.118110  0.118110
2011-08-26 16:00:00         0.803524             0.922558 -0.119034  0.119034
2011-08-26 17:00:00         0.804237             0.924151 -0.119915  0.119915
2011-08-26 18:00:00         0.805158             0.925775 -0.120617  0.120617
2011-08-26 19:00:00         0.806179             0.927400 -0.121221  0.121221
2011-08-26 20:00:00         0.807236             0.929197 -0.121960  0.121960
2011-08-26 21:00:00         0.808481             0.931298 -0.122817  0.122817
2011-08-26 22:00:00         0.810025             0.934017 -0.123992  0.123992
2011-08-26 23:00:00         0.812141             0.938841 -0.126700  0.126700
2011-08-27 00:00:00         0.816546             0.943660 -0.127114  0.127114
       flow, wrf (cms)  flow, t-route (cms)       diff    absdiff
count        24.000000            24.000000  24.000000  24.000000
mean          0.811879             0.914980  -0.103102   0.103102
std           0.007246             0.023804   0.024046   0.024046
min           0.802600             0.858823  -0.127114   0.048387
25%           0.805924             0.909573  -0.120768   0.090102
50%           0.810383             0.921815  -0.114375   0.114375
75%           0.816691             0.929722  -0.090102   0.120768
max           0.827037             0.943660  -0.048387   0.127114


python -m nwm_routing -V2 -f ../../test/input/yaml/Florence_Benchmark.yaml

    for i, d, c in results
ValueError: not enough values to unpack (expected 3, got 2)


python -m nwm_routing -V2 -f ../../test/input/yaml/CustomInput.yaml

                     flow, wrf (cms)  flow, t-route (cms)          diff       absdiff
2018-01-01 02:00:00         0.873438             0.873438 -5.960464e-08  5.960464e-08
2018-01-01 03:00:00         0.873347             0.873347 -1.192093e-07  1.192093e-07
2018-01-01 04:00:00         0.873250             0.873250 -5.960464e-08  5.960464e-08
2018-01-01 05:00:00         0.873148             0.873148 -5.960464e-08  5.960464e-08
2018-01-01 06:00:00         0.873040             0.873040  5.960464e-08  5.960464e-08
2018-01-01 07:00:00         0.872928             0.872928  5.960464e-08  5.960464e-08
2018-01-01 08:00:00         0.872810             0.872810 -5.960464e-08  5.960464e-08
2018-01-01 09:00:00         0.872687             0.872687  0.000000e+00  0.000000e+00
2018-01-01 10:00:00         0.872559             0.872558  1.192093e-07  1.192093e-07
2018-01-01 11:00:00         0.872425             0.872425  1.192093e-07  1.192093e-07
2018-01-01 12:00:00         0.872288             0.872288  2.980232e-07  2.980232e-07
2018-01-01 13:00:00         0.872145             0.872145  0.000000e+00  0.000000e+00
2018-01-01 14:00:00         0.871998             0.871998  5.960464e-08  5.960464e-08
2018-01-01 15:00:00         0.871845             0.871845  5.960464e-08  5.960464e-08
2018-01-01 16:00:00         0.871689             0.871688  1.788139e-07  1.788139e-07
2018-01-01 17:00:00         0.871527             0.871527  1.788139e-07  1.788139e-07
2018-01-01 18:00:00         0.871361             0.871361  1.788139e-07  1.788139e-07
2018-01-01 19:00:00         0.871191             0.871191 -5.960464e-08  5.960464e-08
2018-01-01 20:00:00         0.871015             0.871016 -2.980232e-07  2.980232e-07
2018-01-01 21:00:00         0.870836             0.870837 -3.576279e-07  3.576279e-07
2018-01-01 22:00:00         0.870653             0.870653 -1.192093e-07  1.192093e-07
2018-01-01 23:00:00         0.870465             0.870465 -1.192093e-07  1.192093e-07
2018-01-02 00:00:00         0.870273             0.870273 -2.980232e-07  2.980232e-07
2018-01-02 01:00:00         0.870077             0.870077 -2.384186e-07  2.384186e-07
       flow, wrf (cms)  flow, t-route (cms)          diff       absdiff
count        24.000000            24.000000  2.400000e+01  2.400000e+01
mean          0.871958             0.871958 -2.235174e-08  1.316269e-07
std           0.001042             0.001042  1.665711e-07  1.009371e-07
min           0.870077             0.870077 -3.576279e-07  0.000000e+00
25%           0.871147             0.871147 -1.192093e-07  5.960464e-08
50%           0.872071             0.872071 -2.980232e-08  1.192093e-07
75%           0.872839             0.872839  7.450581e-08  1.788139e-07
max           0.873438             0.873438  2.980232e-07  3.576279e-07


python -m nwm_routing -V2 -f ../../test/input/yaml/Croton_NY_levelpool.yaml

                     flow, wrf (cms)  flow, t-route (cms)          diff       absdiff
2011-08-26 01:00:00         1.445937             1.445937  3.936920e-08  3.936920e-08
2011-08-26 02:00:00         1.446011             1.446011 -2.801819e-08  2.801819e-08
2011-08-26 03:00:00         1.446084             1.446084  3.905945e-08  3.905945e-08
2011-08-26 04:00:00         1.446158             1.446158  2.929993e-08  2.929993e-08
2011-08-26 05:00:00         1.446232             1.446232  3.874969e-08  3.874969e-08
2011-08-26 06:00:00         1.446305             1.446305  2.108307e-08  2.108307e-08
2011-08-26 07:00:00         1.446378             1.446378  7.369995e-09  7.369995e-09
2011-08-26 08:00:00         1.446451             1.446451 -1.029663e-08  1.029663e-08
2011-08-26 09:00:00         1.446523             1.446523  2.966461e-08  2.966461e-08
2011-08-26 10:00:00         1.446595             1.446595  8.044434e-09  8.044434e-09
2011-08-26 11:00:00         1.446667             1.446667  5.633545e-09  5.633545e-09
2011-08-26 12:00:00         1.446739             1.446739  3.222656e-09  3.222656e-09
2011-08-26 13:00:00         1.446811             1.446811 -2.235107e-08  2.235107e-08
2011-08-26 14:00:00         1.446881             1.446881  1.795959e-09  1.795959e-09
2011-08-26 15:00:00         1.446951             1.446951 -3.168488e-08  3.168488e-08
2011-08-26 16:00:00         1.447020             1.447020  3.764343e-09  3.764343e-09
2011-08-26 17:00:00         1.447087             1.447087 -7.112122e-09  7.112122e-09
2011-08-26 18:00:00         1.447154             1.447154  3.173218e-08  3.173218e-08
2011-08-26 19:00:00         1.447218             1.447218  3.950653e-08  3.950653e-08
2011-08-26 20:00:00         1.447282             1.447282 -1.825409e-08  1.825409e-08
2011-08-26 21:00:00         1.447344             1.447344  1.212463e-08  1.212463e-08
2011-08-26 22:00:00         1.447405             1.447405  3.854980e-08  3.854980e-08
2011-08-26 23:00:00         1.447465             1.447465 -1.976929e-08  1.976929e-08
2011-08-27 00:00:00         1.447526             1.447526 -3.966980e-08  3.966980e-08
       flow, wrf (cms)  flow, t-route (cms)          diff       absdiff
count        24.000000            24.000000  2.400000e+01  2.400000e+01
mean          1.446759             1.446759  7.158915e-09  2.192192e-08
std           0.000493             0.000493  2.523996e-08  1.375023e-08
min           1.445937             1.445937 -3.966980e-08  1.795959e-09
25%           1.446360             1.446360 -1.228600e-08  7.875824e-09
50%           1.446775             1.446775  6.501770e-09  2.171707e-08
75%           1.447170             1.447170  3.018150e-08  3.343658e-08
max           1.447526             1.447526  3.950653e-08  3.966980e-08


python -m nwm_routing -V2 -f ../../test/input/yaml/Croton_NY_hybrid_usgs.yaml


                     flow, wrf (cms)  flow, t-route (cms)          diff       absdiff
2011-08-26 01:00:00         1.084535             1.084535 -4.112701e-08  4.112701e-08
2011-08-26 02:00:00         1.084535             1.084535 -4.112701e-08  4.112701e-08
2011-08-26 03:00:00         1.084535             1.084535 -4.112701e-08  4.112701e-08
2011-08-26 04:00:00         1.084535             1.084535 -4.112701e-08  4.112701e-08
2011-08-26 05:00:00         1.084535             1.084535 -4.112701e-08  4.112701e-08
2011-08-26 06:00:00         1.084535             1.084535 -4.112701e-08  4.112701e-08
2011-08-26 07:00:00         1.084535             1.084535 -4.112701e-08  4.112701e-08
2011-08-26 08:00:00         1.084535             1.084535 -4.112701e-08  4.112701e-08
2011-08-26 09:00:00         1.084535             1.084535 -4.112701e-08  4.112701e-08
2011-08-26 10:00:00         1.084535             1.084535 -4.112701e-08  4.112701e-08
2011-08-26 11:00:00         1.084535             1.084535 -4.112701e-08  4.112701e-08
2011-08-26 12:00:00         1.084535             1.084535 -4.112701e-08  4.112701e-08
2011-08-26 13:00:00         1.084535             1.084535 -4.112701e-08  4.112701e-08
2011-08-26 14:00:00         1.084535             1.084535 -4.112701e-08  4.112701e-08
2011-08-26 15:00:00         1.084535             1.084535 -4.112701e-08  4.112701e-08
2011-08-26 16:00:00         1.084535             1.084535 -4.112701e-08  4.112701e-08
2011-08-26 17:00:00         1.084535             1.084535 -4.112701e-08  4.112701e-08
2011-08-26 18:00:00         1.084535             1.084535 -4.112701e-08  4.112701e-08
2011-08-26 19:00:00         1.084535             1.084535 -4.112701e-08  4.112701e-08
2011-08-26 20:00:00         1.084535             1.084535 -4.112701e-08  4.112701e-08
2011-08-26 21:00:00         1.084535             1.084535 -4.112701e-08  4.112701e-08
2011-08-26 22:00:00         1.084535             1.084535 -4.112701e-08  4.112701e-08
2011-08-26 23:00:00         1.084535             1.084535 -4.112701e-08  4.112701e-08
2011-08-27 00:00:00         1.084535             1.084535 -4.112701e-08  4.112701e-08
       flow, wrf (cms)  flow, t-route (cms)          diff       absdiff
count        24.000000            24.000000  2.400000e+01  2.400000e+01
mean          1.084535             1.084535 -4.112701e-08  4.112701e-08
std           0.000000             0.000000  0.000000e+00  0.000000e+00
min           1.084535             1.084535 -4.112701e-08  4.112701e-08
25%           1.084535             1.084535 -4.112701e-08  4.112701e-08
50%           1.084535             1.084535 -4.112701e-08  4.112701e-08
75%           1.084535             1.084535 -4.112701e-08  4.112701e-08
max           1.084535             1.084535 -4.112701e-08  4.112701e-08



python -m nwm_routing -V2 -f ../../test/input/yaml/Croton_NY_rfc.yaml


                     flow, wrf (cms)  flow, t-route (cms)          diff       absdiff
2011-08-26 01:00:00         7.424013             7.424013 -1.378174e-07  1.378174e-07
2011-08-26 02:00:00         7.424013             7.424013 -1.378174e-07  1.378174e-07
2011-08-26 03:00:00         8.681314             8.681314 -4.683838e-07  4.683838e-07
2011-08-26 04:00:00         8.681314             8.681314 -4.683838e-07  4.683838e-07
2011-08-26 05:00:00         8.681314             8.681314 -4.683838e-07  4.683838e-07
2011-08-26 06:00:00         8.681314             8.681314 -4.683838e-07  4.683838e-07
2011-08-26 07:00:00         8.681314             8.681314 -4.683838e-07  4.683838e-07
2011-08-26 08:00:00         8.681314             8.681314 -4.683838e-07  4.683838e-07
2011-08-26 09:00:00         8.681314             8.681314 -4.683838e-07  4.683838e-07
2011-08-26 10:00:00         8.681314             8.681314 -4.683838e-07  4.683838e-07
2011-08-26 11:00:00         8.681314             8.681314 -4.683838e-07  4.683838e-07
2011-08-26 12:00:00         8.681314             8.681314 -4.683838e-07  4.683838e-07
2011-08-26 13:00:00         8.681314             8.681314 -4.683838e-07  4.683838e-07
2011-08-26 14:00:00         8.681314             8.681314 -4.683838e-07  4.683838e-07
2011-08-26 15:00:00         8.681314             8.681314 -4.683838e-07  4.683838e-07
2011-08-26 16:00:00         8.681314             8.681314 -4.683838e-07  4.683838e-07
2011-08-26 17:00:00         8.681314             8.681314 -4.683838e-07  4.683838e-07
2011-08-26 18:00:00         8.681314             8.681314 -4.683838e-07  4.683838e-07
2011-08-26 19:00:00         8.681314             8.681314 -4.683838e-07  4.683838e-07
2011-08-26 20:00:00         8.681314             8.681314 -4.683838e-07  4.683838e-07
2011-08-26 21:00:00         8.681314             8.681314 -4.683838e-07  4.683838e-07
2011-08-26 22:00:00         8.681314             8.681314 -4.683838e-07  4.683838e-07
2011-08-26 23:00:00         8.681314             8.681314 -4.683838e-07  4.683838e-07
2011-08-27 00:00:00         8.681314             8.681314 -4.683838e-07  4.683838e-07
       flow, wrf (cms)  flow, t-route (cms)          diff       absdiff
count        24.000000            24.000000  2.400000e+01  2.400000e+01
mean          8.576539             8.576539 -4.408366e-07  4.408366e-07
std           0.354974             0.354974  9.332876e-08  9.332876e-08
min           7.424013             7.424013 -4.683838e-07  1.378174e-07
25%           8.681314             8.681314 -4.683838e-07  4.683838e-07
50%           8.681314             8.681314 -4.683838e-07  4.683838e-07
75%           8.681314             8.681314 -4.683838e-07  4.683838e-07
max           8.681314             8.681314 -1.378174e-07  4.683838e-07

**Comment by jhrehanoaa** [comment]
turning courant to false for the failed test case works. 

                    flow, wrf (cms)  flow, t-route (cms)          diff       absdiff
2018-09-01 00:00:00         0.000549             0.000550 -1.517237e-06  1.517237e-06
2018-09-01 01:00:00         0.000551             0.000551 -2.094862e-07  2.094862e-07
2018-09-01 02:00:00         0.000551             0.000551 -2.910431e-08  2.910431e-08
2018-09-01 03:00:00         0.000551             0.000551 -3.957417e-09  3.957417e-09
2018-09-01 04:00:00         0.000572             0.000572 -6.371263e-10  6.371263e-10
...                              ...                  ...           ...           ...
2018-09-30 19:00:00         0.003900             0.003900 -1.365566e-12  1.365566e-12
2018-09-30 20:00:00         0.004174             0.004174  1.702340e-10  1.702340e-10
2018-09-30 21:00:00         0.004482             0.004482  2.286799e-10  2.286799e-10
2018-09-30 22:00:00         0.004556             0.004556 -8.823395e-12  8.823395e-12
2018-09-30 23:00:00         0.004353             0.004353  3.173046e-11  3.173046e-11

[720 rows x 4 columns]
       flow, wrf (cms)  flow, t-route (cms)          diff       absdiff
count       720.000000           720.000000  7.200000e+02  7.200000e+02
mean          0.007270             0.007270 -4.815647e-07  1.664529e-06
std           0.032130             0.032134  3.205795e-05  3.201827e-05
min           0.000423             0.000423 -7.499759e-04  8.349398e-14
25%           0.000674             0.000674 -3.102532e-11  1.833097e-11
50%           0.001849             0.001849  4.492251e-12  4.494609e-11
75%           0.003979             0.003979  1.048783e-10  2.539217e-10
max           0.467868             0.467448  4.201221e-04  7.499759e-04

**Comment by jameshalgren** [comment]
supersedes #344

**Comment by jameshalgren** [comment]
@awlostowski-noaa @kumdonoaa
A high-level thought/question 
As a pattern for moving forward, what would you think of adding a `compute_kernel` flag option `diff-TU` and leaving the `diff-internal-length-equlalize` in place as a second option? (I haven't fully examined for myself yet what the implications of that would be -- I can see impacts in at least three areas: 1) compile changes (we'll want to have diffusive.pyx and the diffusive.f90 get  renamed to something matching the kernel flag option and there would be two of them); 2) input and workflow changes to allow for both; 3) any kernel changes to the old kernel to keep it compatible with the new update. 

I think keeping a parallel structure could promote a more effective collaboration as we hope that there will be additional updates  and possibly even completely different diffusive or dynamic kernels. Perhaps that could be benefitted if we start now with having several of them cleanly coexisting.

If the idea is attractive, but the work to make this happen within this PR is beyond our capacity at the moment, we could perhaps park it as an issue to happen later.

**Review by jameshalgren — APPROVED** [review]
Confirmed functional tests and no external impact...

**Review by jameshalgren — APPROVED** [review]
Review performed on un-pushed rebase -- now correct.

**Pull request merged**
