### PR TITLE
Reservoir package merge

### PR DESCRIPTION
**Pull request by hellkite500**
replaces #311 rebased with latest master, ~~missing some integration with the main calling/compute_nhd_v02 function.~~ Now integrated with the calling function. 

Added a test case for the Croton level pool and rfc reservoir types using the new V3 input file structure.
Manually incorporated the changes to former `compute_nhd_routing_v02.py` script in #311 into appropriate locations in `__main__.py` and `compute.py`

#!/bin/bash -x
- [x] python -m nwm_routing -V2  -f ../../test/input/yaml/CustomInput.yaml
- [x] python -m nwm_routing -V3  -f ../../test/input/yaml/CustomInput_loop.yaml
- [ ]  python -m nwm_routing -V2 -f ../../test/input/yaml/Croton_NY_with_wb_dev.yaml -- currently fails with input error; planning to deprecate, will not fix.
- [x] python -m nwm_routing -V2  -f ../../test/input/yaml/Croton_NY_levelpool.yaml
- [x] python -m nwm_routing -V3  -f ../../test/input/yaml/Croton_NY_levelpool_loop.yaml
- [x] python -m nwm_routing -V2  -f ../../test/input/yaml/Croton_NY_rfc.yaml
- [x] python -m nwm_routing -V3  -f ../../test/input/yaml/Croton_NY_rfc_loop.yaml
- [x] python -m nwm_routing -V2  -f ../../test/input/yaml/Croton_NY_hybrid_usgs.yaml
- [ ] python -m nwm_routing -V3  -f ../../test/input/yaml/Croton_NY_hybrid_usgs_loop.yaml -- Not created yet
- [ ] python -m nwm_routing -V2  --test pocono1 -t -v --debuglevel 1
- [ ] python -m nwm_routing -V2  -t -n Mainstems_CONUS -v --debuglevel 1 --parallel by-network --nts 288 --cpu-pool 6 
- [ ] python -m nwm_routing -V2  -t -n Mainstems_CONUS -v --debuglevel 1 --parallel by-subnetwork-jit-clustered --subnet-size 100 --nts 288 --cpu-pool 6
- [ ] python -m nwm_routing -V2  -f ../../test/input/yaml/Florence_Benchmark.yaml
- [x] python -m nwm_routing -V2  -f ../../test/input/yaml/Florence_Benchmark_diff.yaml

### CODE REVIEW

**Review by jameshalgren — APPROVED** [review]
Approving. Tests passing are noted in the PR description. Remaining unpassed tests need to be debugged

**Comment by jhrehanoaa** [comment]
I tried compiling with the new updates and keep hitting a missing netcdf.mod file error. Is there anything special I need to do in order to update to the new master branch?

**Comment by jdmattern-noaa** [comment]
> I tried compiling with the new updates and keep hitting a missing netcdf.mod file error. Is there anything special I need to do in order to update to the new master branch?

@jhrehanoaa There are a couple of updates to the reservoirs makefile and compiler.sh that were evidently not committed. I will submit a PR with those in a few min.

**Comment by jhrehanoaa** [comment]
> > I tried compiling with the new updates and keep hitting a missing netcdf.mod file error. Is there anything special I need to do in order to update to the new master branch?
> 
> @jhrehanoaa There are a couple of updates to the reservoirs makefile and compiler.sh that were evidently not committed. I will submit a PR with those in a few min.

Okay, that sounds good. I appreciate it.

**Pull request merged**
